### ISSUE TITLE
Cannot list VMWare VMs with the "gns3" user

### ISSUE THREAD

**Issue by Abyss-W4tcher** [mother/gns3-docs#74]
Hi,

I followed this tutorial to install gns3 on a remote Ubuntu 22.04 server : https://docs.gns3.com/docs/getting-started/installation/remote-server/. I also installed VMWare Workstation. 

However, gns wasn't listing any of my VMs running in VMWare. After some time, I found that gns3server was ran by the "gns3" user (https://raw.githubusercontent.com/GNS3/gns3-server/master/scripts/remote-install.sh).

If I run `gns3server` with my main user, I can find my VMs in the list. I gave full RWX to gns3 user on my vmware folder, or even setup a shared vm folder with a dedicated user group, but it doesn't work. I also added the line "prefvmx.defaultvmpath" to "/etc/vmware/config" but still doesn't help. 

As I don't really know how the gns3server is listing the VMs (api I guess), I can't provide a good fix, except running gns3 with my main user.  Can you help me so that we can update the doc and write a procedure to setup the permissions ?

Thanks !

**Comment by grossmj** [comment]
I think the server looks in `~/.vmware/inventory.vmls` to find the VMs. Can you confirm your VMs are listed in the file?


________________________________
From: Abyss Watcher ***@***.***>
Sent: Wednesday, May 31, 2023 11:15:26 PM
To: mother/gns3-docs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mother/gns3-docs] Cannot list VMWare VMs with the "gns3" user (Issue #74)


Hi,

I followed this tutorial to install gns3 on a remote Ubuntu 22.04 server : https://docs.gns3.com/docs/getting-started/installation/remote-server/. I also installed VMWare Workstation.

However, gns wasn't listing any of my VMs running in VMWare. After some time, I found that gns3server was ran by the "gns3" user (https://raw.githubusercontent.com/GNS3/gns3-server/master/scripts/remote-install.sh).

If I run gns3server with my main user, I can find my VMs in the list. I gave full RWX to gns3 user on my vmware folder, or even setup a shared vm folder with a dedicated user group, but it doesn't work. I also added the line "prefvmx.defaultvmpath" to "/etc/vmware/config" but still doesn't help.

As I don't really know how the gns3server is listing the VMs (api I guess), I can't provide a good fix, except running gns3 with my main user. Can you help me so that we can update the doc and write a procedure to setup the permissions ?

Thanks !

**Comment by Abyss-W4tcher** [comment]
> 

I managed to have something working by switching the gns3server.service to my main user. I can see my VMs listed in my "~/.vmware/inventory.vmls", so I guess the ".vmware" directory also needs to be readable by the "gns3" user.
